# Base URL for the API
@baseUrl = http://localhost:3000

### Create a new note
POST {{baseUrl}}/notes
Content-Type: application/json

{
  "title": "My First Note",
  "content": "This is the content of my first note."
}

### Attempt to create a duplicate note should fail
POST {{baseUrl}}/notes
Content-Type: application/json

{
  "title": "My First Note",
  "content": "This is the content of my first note."
}

### Fetch all notes
GET {{baseUrl}}/notes
Content-Type: application/json

### Get a note by ID
GET {{baseUrl}}/notes/1
Content-Type: application/json

### Update a note by ID
PUT {{baseUrl}}/notes/1
Content-Type: application/json

{
  "title": "Updated Note",
  "content": "This is the updated content of the note."
}

### Delete a note by ID
DELETE {{baseUrl}}/notes/7
Content-Type: application/json